# Run in the PDS Tcl console AFTER creating an empty PG2L100H/FBG484 project.
# Paths are relative to this script, so the checkout can be moved.
set stereo_src_root [file dirname [file normalize [info script]]]
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
add_design [file normalize [file join $stereo_src_root "image_pcie_capture.v"]]
add_design [file normalize [file join $stereo_src_root "stereo_camera_top.v"]]
add_design [file normalize [file join $stereo_src_root "stereo_axi_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "stereo_reg_config.v"]]
add_design [file normalize [file join $stereo_src_root "stereo_i2c_com.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ipm_distributed_sdpram_v1_2.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_controller.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_cpld_tx_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_mrd_tx_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_mwr_tx_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rd_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_cpld_wr_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_mwr_wr_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_top.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tlp_rcv.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tlp_tx_mux.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_cpld_rd_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_mwr_rd_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_top.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_wr_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/fifo/ipm_distributed_sdpram_v1_2_distributed_fifo.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_ctrl.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_v1_2.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_ram/ips2l_pcie_dma_ram.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ipm2l_sdpram_v1_1_ips2l_pcie_dma_ram.v"]]
add_design [file normalize [file join $stereo_src_root "../source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ips2l_pcie_dma_ram_init_param.v"]]
add_design [file normalize [file join $stereo_src_root "../source/ov5640/rtl/cmos_capture_data.v"]]
add_design [file normalize [file join $stereo_src_root "../project/ipcore/ddr3/ddr3.idf"]]
add_design [file normalize [file join $stereo_src_root "../project/ipcore/clk_1080p_gen/clk_1080p_gen.idf"]]
add_design [file normalize [file join $stereo_src_root "../project/ipcore/pcie_test/pcie_test.idf"]]
add_design [file normalize [file join $stereo_src_root "../project/ipcore/W_FIFO_16i_128o/W_FIFO_16i_128o.idf"]]
add_design [file normalize [file join $stereo_src_root "../project/ipcore/R_FIFO_128i_128o/R_FIFO_128i_128o.idf"]]
add_constraint [file join $stereo_src_root "stereo_j8.fdc"]
# Next: compile -top_module image_pcie_capture, then synthesize, map, place/route.
