"""Generate the isolated J8 bring-up sources/constraints from the checked-in design.

Does not edit the three-camera FPGA project or run PDS. Run from any directory.
The generated top keeps the original DDR/PCIe instance names for their constraints.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "fpga/fpga_pcie_ov5640"
OUT = BASE / "stereo_j8"
OUT.mkdir(exist_ok=True)

def write(name, text):
    (OUT / name).write_bytes(text.encode("utf-8"))

top = (BASE / "source/image_pcie_capture.v").read_text(encoding="utf-8")
# The camera-only test has no HMI, FSPI or movement commands. Keep the existing
# movement pins driven inactive, rather than leaving a former active-low output low.
top = re.sub(r"    //coms2\n.*?    //coms5", "    //coms5", top, count=1, flags=re.S)
top = re.sub(r"    //fspi\n.*?\n\);", """    // Existing vehicle outputs remain inactive during this video-only test.
    output wire go, back, left, right, stop
);""", top, count=1, flags=re.S)
top = top.replace("    output reg        ref_led,", "")
top = re.sub(r"  wire \[31:0\] cmos[256]_pclk_count;[^\n]*\n", "", top)
top = re.sub(r"  // UART signals\n.*?  assign cfg_ido_req_en", "  reg ref_led;\n  assign cfg_ido_req_en", top, count=1, flags=re.S)
a = top.index("  //===================================================================================================================\n  //fspi")
b = top.index("  //*==============================================================================\n  //ddr3 IP", a)
camera = """  assign {go, back, left, right, stop} = 5'b11111;
  wire video5_clk, video5_vs, video5_de;
  wire video6_clk, video6_vs, video6_de;
  wire [15:0] video5_data, video6_data;
  stereo_camera_top u_ov5640_top (
      .sys_clk(free_clk), .reset_n(board_rst_n),
"""
for n in (5, 6):
    camera += "".join(f"      .cmos{n}_{x}(cmos{n}_{x}),\n" for x in ("scl", "sda", "vsync", "href", "pclk", "data", "reset"))
    camera += "".join(f"      .video{n}_{x}(video{n}_{x}),\n" for x in ("clk", "vs", "de", "data"))
camera = camera.rstrip(",\n") + "\n  );\n\n"
top = top[:a] + camera + top[b:]
top = top.replace("axi4_ctrl_3ch #(", "stereo_axi_ctrl #(")
top = top.replace(".wframe_pclk({video6_clk, video5_clk, video2_clk})", ".wframe_pclk({video6_clk, video5_clk, video5_clk})")
top = top.replace(".wframe_vsync({~video6_vs, ~video5_vs, ~cnn_frame_vsync})", ".wframe_vsync({~video6_vs, ~video5_vs, ~video5_vs})")
top = top.replace(".wframe_data_en({video6_de, video5_de, cnn_frame_de})", ".wframe_data_en({video6_de, video5_de, video5_de})")
top = top.replace(".wframe_data0(cnn_rgb_16bit)", ".wframe_data0(video5_data)").replace(".wframe_data1(video5_data)", ".wframe_data1(16'h0000)")
top = "// GENERATED by scripts/prepare_stereo_j8.py. J8 CAM1=left, CAM2=right.\n" + top
write("image_pcie_capture.v", top)

axi = "`timescale 1ns / 1ps\n" + (BASE / "source/axi_ctrl/axi4_ctrl_3ch.v").read_text(encoding="utf-8")
axi = axi.replace("module axi4_ctrl_3ch", "module stereo_axi_ctrl")
axi = re.sub(r"parameter C_START_MASK[^\n]+", "parameter C_START_MASK = 0 // raw DVP: do not apply the CNN-era 623-pixel shift", axi)
# Initialize pixel counters without relying on a camera VSYNC at FPGA power-up.
axi = axi.replace("always @(posedge wframe_pclk[gi]) begin\n        r_vsync_d", "always @(posedge wframe_pclk[gi] or posedge axi_reset) begin\n        if (axi_reset) begin\n          r_vsync_d[gi] <= 0; pix_h[gi] <= 0; pix_v[gi] <= 0;\n        end else begin\n        r_vsync_d", 1)
axi = axi.replace("else pix_h[gi] <= pix_h[gi] + 1;\n        end\n      end", "else pix_h[gi] <= pix_h[gi] + 1;\n        end\n        end\n      end", 1)
# Snapshot a separate completed bank for each camera at the read-frame boundary.
# Independent OV5640 oscillators/counters must not be forced to share a bank index.
a = axi.index("  reg [ 1:0] rc_rframe_index;")
b = axi.index("  reg  rframe_vsync_dly;", a)
axi = axi[:a] + """  reg [1:0] read_bank [2:0];
  reg [2:0] read_ready;
  integer rb;
""" + axi[b:]
needle = "  reg [1:0] rd_state;"
axi = axi.replace("  reg r_rfifo_rst_axi;", "")
axi = axi.replace(needle, """  // w_rfifo_rst also marks the start of each PCIe image read.
  reg r_rfifo_rst_axi;
  always @(posedge axi_clk or posedge axi_reset) begin
    if (axi_reset) begin
      read_ready <= 0;
      for (rb=0; rb<3; rb=rb+1) read_bank[rb] <= 0;
    end else if (r_rfifo_rst_axi) begin
      for (rb=0; rb<3; rb=rb+1) begin
        read_bank[rb] <= abs_frame_cnt[rb][1:0] - 2'd2;
        read_ready[rb] <= (abs_frame_cnt[rb] >= 3);
      end
    end
  end

""" + needle)
# A DDR burst is 160 bytes (80 pixels), never crosses a 320-pixel tile edge.
axi = axi.replace("  assign axi_araddr = C_BASE_ADDR + (rc_rframe_index * FRAME_SIZE_BYTES) + araddr_offset;", """  wire [1:0] read_slot = (araddr_offset >= 240 * LINE_STRIDE) ?
                            ((araddr_offset % LINE_STRIDE >= 640) ? 2'd3 : 2'd2) :
                            ((araddr_offset % LINE_STRIDE >= 640) ? 2'd1 : 2'd0);
  wire [1:0] read_channel = (read_slot == 3) ? 2'd0 : read_slot;
  assign axi_araddr = C_BASE_ADDR + (read_bank[read_channel] * FRAME_SIZE_BYTES) + araddr_offset;""")
axi = axi.replace("rfifo_wdata <= axi_rdata;", "rfifo_wdata <= read_ready[read_channel] ? axi_rdata : {C_DATA_LEN{1'b0}};")
axi = axi.replace("assign tp_o = {ws_state, cur_ch, min_abs_cnt[3:0], wr_idx[0], wr_idx[1], wr_idx[2]};", "assign tp_o = {18'd0, ws_state, cur_ch, read_ready, read_bank[0], read_bank[1], read_bank[2]};")
write("stereo_axi_ctrl.v", axi)

# Same vendor register table, deterministic reset even when the divided clock is
# held low, honor the power-on delay, and do not treat NACK as configuration done.
cfg = (BASE / "source/ov5640/rtl/reg_config.v").read_text(encoding="utf-8")
cfg = cfg.replace("module reg_config", "module stereo_reg_config").replace("  i2c_com u1", "  wire ack, tr_end;\n  stereo_i2c_com u1")
cfg = cfg.replace("always @(posedge clock_20k)", "always @(posedge clock_20k or negedge camera_rstn)")
cfg = cfg.replace("if (reg_conf_done_reg == 1'b0)", "if (initial_en && reg_conf_done_reg == 1'b0)")
cfg = cfg.replace("reg_index   <= reg_index + 1'b1;", "if (!ack) reg_index <= reg_index + 1'b1;")
write("stereo_reg_config.v", cfg)
i2c = "`timescale 1ns / 1ps\n" + (BASE / "source/ov5640/rtl/i2c_com.v").read_text(encoding="utf-8")
i2c = i2c.replace("module i2c_com", "module stereo_i2c_com").replace("reg ack1,ack2,ack3;", "reg ack0,ack1,ack2,ack3;")
i2c = i2c.replace("assign ack=ack1|ack2|ack3;", "assign ack=ack0|ack1|ack2|ack3;")
i2c = i2c.replace("always@(posedge clock_i2c)", "always@(posedge clock_i2c or negedge camera_rstn)")
i2c = i2c.replace("ack1<=1;", "ack0<=1;ack1<=1;").replace("i2c_data[23];ack1<=", "i2c_data[23];ack0<=")
write("stereo_i2c_com.v", i2c)

# Preserve board DDR and PCIe constraints, remove ports absent from this top.
fdc = (BASE / "project/project.fdc").read_text(encoding="utf-8")
lines = []
for line in fdc.splitlines():
    if line.lstrip().startswith("#") or not line.strip(): continue
    if re.search(r"cmos[12]_|p:spi_|p:RXD|p:ref_led|clk_50M", line): continue
    if "{PAP_IO_UNUSED}" in line: continue
    if "p:board_rst_n" in line or "p:perst_n" in line:
        line = line.replace("{PAP_IO_VCCIO} {3.3}", "{PAP_IO_VCCIO} {1.8}")
    if "p:pclk_led" in line:
        line = line.replace("{J16}", "{M17}").replace("{LVCMOS33}", "{LVCMOS18}").replace("{PAP_IO_VCCIO} {3.3}", "{PAP_IO_VCCIO} {1.8}")
    lines.append(line)
for key, value in [("PAP_IO_DIRECTION","OUTPUT"),("PAP_IO_LOC","J16"),("PAP_IO_VCCIO","1.8"),("PAP_IO_STANDARD","LVCMOS18")]:
    lines.append(f"define_attribute {{p:heart_beat_led}} {{{key}}} {{{value}}}")
lines += [
    "create_generated_clock -name {camera_cfg25} -source [get_ports {free_clk}] [get_pins {u_ov5640_top/u_pll/clkout1}] -multiply_by {1}",
    "create_generated_clock -name {camera_reset50} -source [get_ports {free_clk}] [get_pins {u_ov5640_top/u_pll/clkout2}] -multiply_by {2}",
]
write("stereo_j8.fdc", "# J8: board manual PDF pp24-25 + DOUBLE-DVP-OV5640 schematic J17.\n# DDR/PCIe placement inherited from project/project.fdc; top hierarchy preserved.\n# Camera PCLK 56 MHz is inherited; measure it during bring-up.\n" + "\n".join(lines) + "\n")
write("camera_pins_only.fdc", "# REVIEW ONLY: already included in stereo_j8.fdc; do not import both.\n" +
      "\n".join(line for line in lines if re.search(r"p:cmos[56]_", line)) + "\n")

# Keep only real synthesis sources, not testbenches/example tops or generated copies.
pds = (BASE / "project/project.pds").read_text(encoding="utf-8")
raw = re.findall(r'\(_file "([^"]+)"', pds.split("(_widget wgt_import_logic_con_file")[0])
files = ["image_pcie_capture.v", "stereo_camera_top.v", "stereo_axi_ctrl.v", "stereo_reg_config.v", "stereo_i2c_com.v"]
for f in raw:
    if "/source/pcie/" in f or f.endswith("/cmos_capture_data.v"):
        files.append(f)
ips = [f"../project/ipcore/{n}/{n}.idf" for n in ["ddr3", "clk_1080p_gen", "pcie_test", "W_FIFO_16i_128o", "R_FIFO_128i_128o"]]
write("design_files.txt", "\n".join(files + ips) + "\n")
tcl = """# Run in the PDS Tcl console AFTER creating an empty PG2L100H/FBG484 project.
# Paths are relative to this script, so the checkout can be moved.
# Change only the path in your source {...} command on another computer.
# PGL50H/Logos is NOT a substitute for PG2L100H/Logos2.
set stereo_src_root [file dirname [file normalize [info script]]]
set stereo_design_files {
"""
for f in files + ips:
    tcl += f'    {{{f}}}\n'
tcl += """}
# Fail before changing the project if the copied source tree is incomplete.
set stereo_missing {}
foreach rel [concat $stereo_design_files {stereo_j8.fdc}] {
    set path [file normalize [file join $stereo_src_root $rel]]
    if {![file isfile $path] || ![file readable $path]} {
        lappend stereo_missing $path
    }
}
if {[llength $stereo_missing] != 0} {
    error "Incomplete stereo source tree. Copy stereo_j8, source and project/ipcore together. Missing/unreadable:\\n[join $stereo_missing \\n]"
}
foreach command {set_arch add_design add_constraint} {
    if {[llength [info commands $command]] == 0} {
        error "PDS command '$command' is unavailable. Run this script inside PDS Tcl Console with an empty project open."
    }
}
if {[catch {set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484} stereo_arch_error]} {
    error "Cannot select the required PG2L100H-6/FBG484 (Logos2). Check the open project, PDS version, device support and license. Do NOT substitute PGL50H/Logos. Original PDS error: $stereo_arch_error"
}
foreach rel $stereo_design_files {
    add_design [file normalize [file join $stereo_src_root $rel]]
}
add_constraint [file join $stereo_src_root "stereo_j8.fdc"]
puts "Stereo J8 import complete: [llength $stereo_design_files] design entries + 1 FDC. Verify PG2L100H, FBG484, -6 in Project Settings."
"""
tcl += '# Next: compile -top_module image_pcie_capture, then synthesize, map, place/route.\n'
write("add_sources.tcl", tcl)
for f in files + ips:
    if not (OUT / f).is_file(): raise SystemExit(f"Missing required source: {f}")
print(f"Prepared {len(files)} HDL files + {len(ips)} IP descriptors in {OUT}")
