#!/usr/bin/env python3
"""Create the full three-cameras-per-board top from the reviewed stereo PCIe shell.
Does not modify legacy/stereo projects or any vendor IP. Run from any directory.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / 'fpga/fpga_pcie_ov5640'
OUT = BASE / 'drive_6ch'
OUT.mkdir(exist_ok=True)
def read(p): return p.read_text(encoding='utf-8')
def write(n,s): (OUT/n).write_text(s,encoding='utf-8',newline='\n')
top = read(BASE/'stereo_j8/image_pcie_capture.v')
top = top.replace('// GENERATED by scripts/prepare_stereo_j8.py. J8 CAM1=left, CAM2=right.',
                  '// GENERATED by scripts/prepare_drive_6ch.py. q0=cmos2, q1=cmos5, q2=cmos6.')
port = top[top.index('    inout        cmos5_scl'):top.index('    //coms6')]
top = top.replace('    //coms5', port.replace('cmos5','cmos2')+'    //coms5',1)
top = top.replace('    output go, back, left, right, stop',
                  '    input spi_clk, spi_cs, RXD,\n    inout [3:0] spi_data,\n    output go, back, left, right, stop')
# Prior template may have the wire keyword; verify ports instead of silently omitting them.
if 'input spi_clk' not in top:
    top=top.replace('    output wire go, back, left, right, stop',
                    '    input spi_clk, spi_cs, RXD,\n    inout [3:0] spi_data,\n    output wire go, back, left, right, stop')
assert 'input spi_clk' in top
start=top.index("  assign {go, back, left, right, stop}")
end=top.index('  //*====',start)
ports=[];logic=['  wire [127:0] hmi_cfg; wire [7:0] rx_byte; wire rx_valid; wire [2:0] camera_ok;',
 '  uart_rx #(.CLK_FREQ(25000000),.UART_BPS(115200)) hmi_rx(.clk(free_clk),.rst_n(board_rst_n),.uart_rxd(RXD),.uart_rx_done(rx_valid),.uart_rx_data(rx_byte));',
 '  hmi_regs hmi(.clk(free_clk),.rst_n(board_rst_n),.valid(rx_valid),.data(rx_byte),.cfg(hmi_cfg));',
 '  safe_fspi bus(.clk(free_clk),.rst_n(board_rst_n),.spi_clk(spi_clk),.spi_cs(spi_cs),.spi_data(spi_data),.view(hmi_cfg[127:120]),.camera_ok(camera_ok),.go(go),.back(back),.left(left),.right(right),.stop(stop));']
for i,n in enumerate((2,5,6)):
    logic += [f'  wire video{n}_clk,video{n}_vs,video{n}_de,isp{n}_vs,isp{n}_de;',
              f'  wire [15:0] video{n}_data,isp{n}_data;',
              f'  night_isp isp{n}(.clk(video{n}_clk),.rst_n(board_rst_n),.vs(video{n}_vs),.de(video{n}_de),.rgb(video{n}_data),.cfg(hmi_cfg),.ovs(isp{n}_vs),.ode(isp{n}_de),.out(isp{n}_data));',
              f'  camera_health health{n}(.clk(free_clk),.rst_n(board_rst_n),.pclk(video{n}_clk),.vs(video{n}_vs),.de(video{n}_de),.alive(camera_ok[{i}]));']
    for suffix in ('scl','sda','vsync','href','pclk','data','reset'):
        ports.append(f'.cmos{n}_{suffix}(cmos{n}_{suffix})')
    for suffix in ('clk','vs','de','data'): ports.append(f'.video{n}_{suffix}(video{n}_{suffix})')
logic += ['  drive_camera_top u_ov5640_top(.sys_clk(free_clk),.reset_n(board_rst_n),\n      '+',\n      '.join(ports)+');\n']
top=top[:start]+'\n'.join(logic)+'\n'+top[end:]
top=top.replace('.wframe_pclk({video6_clk, video5_clk, video5_clk})','.wframe_pclk({video6_clk, video5_clk, video2_clk})')
top=top.replace('.wframe_vsync({~video6_vs, ~video5_vs, ~video5_vs})','.wframe_vsync({~isp6_vs, ~isp5_vs, ~isp2_vs})')
top=top.replace('.wframe_data_en({video6_de, video5_de, video5_de})','.wframe_data_en({isp6_de, isp5_de, isp2_de})')
top=top.replace('.wframe_data0(video5_data)','.wframe_data0(isp2_data)').replace(".wframe_data1(16'h0000)",'.wframe_data1(isp5_data)').replace('.wframe_data2(video6_data)','.wframe_data2(isp6_data)')
top=top.replace('// Existing vehicle outputs remain inactive during this video-only test.', '// Active-low motor outputs are gated by safe_fspi watchdog and camera health.')
write('image_pcie_capture.v',top)
cam=read(BASE/'stereo_j8/stereo_camera_top.v').replace('module stereo_camera_top','module drive_camera_top')
port=cam[cam.index('    inout cmos5_scl'):cam.index('    inout cmos6_scl')]
cam=cam.replace('    inout cmos5_scl',port.replace('cmos5','cmos2')+'    inout cmos5_scl',1)
cam=cam.replace('    output video5_clk','    output video2_clk,output video2_vs,output video2_de,output [15:0] video2_data,\n    output video5_clk',1)
cam=cam.replace('    wire init5, init6, scl5, scl6;','    wire init2, init5, init6, scl2, scl5, scl6;\n    assign cmos2_reset=cmos5_reset;\n    assign cmos2_scl=scl2?1\'bz:1\'b0;')
cfg=cam[cam.index('    stereo_reg_config cfg5'):cam.index('    stereo_reg_config cfg6')]
cam=cam.replace('    stereo_reg_config cfg5',cfg.replace('cfg5','cfg2').replace('cmos5','cmos2').replace('init5','init2').replace('scl5','scl2')+'    stereo_reg_config cfg5',1)
capture=cam[cam.index('    cmos_capture_data capture5'):cam.index('    cmos_capture_data capture6')]
cam=cam.replace('    cmos_capture_data capture5',capture.replace('capture5','capture2').replace('cmos5','cmos2').replace('init5','init2').replace('video5','video2')+'    cmos_capture_data capture5',1)
cam=cam.replace('    assign video5_clk', '    assign video2_clk=cmos2_pclk;\n    assign video5_clk',1)
write('drive_camera_top.v',cam)
fdc=read(BASE/'stereo_j8/stereo_j8.fdc')
original=read(BASE/'project/project.fdc')
extra=[l for l in original.splitlines() if not l.lstrip().startswith('#') and re.search(r'p:cmos2_|p:spi_|p:RXD|\{cmos2_pclk\}',l)]
write('drive_6ch.fdc','# Full drive_6ch: inherited verified board pins; no substitutions.\n'+fdc+'\n'+'\n'.join(extra)+'\n')
tcl=read(BASE/'stereo_j8/add_sources.tcl')
tcl=tcl.replace('{stereo_camera_top.v}','{drive_camera_top.v}\n    {hmi_regs.v}\n    {night_isp.v}\n    {camera_health.v}\n    {safe_fspi.v}\n    {../source/uart_lcd/uart_rx.v}')
for n in ('stereo_axi_ctrl','stereo_reg_config','stereo_i2c_com'):
    tcl=tcl.replace('{'+n+'.v}','{../stereo_j8/'+n+'.v}')
tcl=tcl.replace('stereo_j8.fdc','drive_6ch.fdc').replace('Stereo J8','Full drive_6ch').replace('stereo_j8, source and project/ipcore','drive_6ch, stereo_j8, source and project/ipcore')
write('add_sources.tcl',tcl)
print('Generated drive_6ch top, camera wrapper, FDC and import Tcl. Reused stereo transport/configuration fixes.')
